#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://github.com/facebook/zstd/archive/refs/tags/v1.5.2.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make coreutils"
export ZOPEN_BOOTSTRAP=skip
export ZOPEN_CONFIGURE=skip
export ZSTD_NO_ASM=1

export ZOPEN_INSTALL_OPTS="install POSIX_ENV=Yes prefix=\${ZOPEN_INSTALL_DIR}" 

export ZOPEN_NAME="zstd-1.5.2"
rm -f v1.5.2
ln -s ${ZOPEN_NAME} v1.5.2

zopen_check_results()
{
  return 3 # non-functional
}

