#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
if ! [ -f ./buildenv ]; then
	echo "Need to source from the buildenv directory" >&2
	return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://github.com/facebook/zstd/archive/refs/tags/v1.5.2.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make coreutils"
export ZOPEN_EXTRA_CFLAGS='-qnocsect'
export ZOPEN_BOOTSTRAP=skip
export ZOPEN_CONFIGURE=skip
export ZSTD_NO_ASM=1

export ZOPEN_INSTALL_OPTS="install POSIX_ENV=Yes prefix=\${ZOPEN_INSTALL_DIR}" 

rm -f v1.5.2
ln -s zstd-1.5.2 v1.5.2
